### ISSUE TITLE
Error while reproducing

### ISSUE THREAD

**Issue by bareblackfoot** [TheShadow29/zsgnet-pytorch#8]
Firstly, I really appreciate your great work! 

While reproducing your work on the flickr30k dataset, an error occurred.
I think it is because I changed "train_flat.csv" to "train.csv" in ds_info.json, since I don't have train_flat.csv. 
Please see the error and help me.

Error traceback:
------------------------------------
Traceback (most recent call last):
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/blackfoot/PycharmProjects/zsgnet-pytorch/code/main_dist.py", line 101, in <module>
    fire.Fire(main_dist)
  File "/home/blackfoot/.local/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/blackfoot/.local/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/blackfoot/.local/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/blackfoot/PycharmProjects/zsgnet-pytorch/code/main_dist.py", line 89, in main_dist
    learn = learner_init(uid, cfg)
  File "/home/blackfoot/PycharmProjects/zsgnet-pytorch/code/main_dist.py", line 20, in learner_init
    data = get_data(cfg)
  File "/home/blackfoot/PycharmProjects/zsgnet-pytorch/code/dat_loader.py", line 237, in get_data
    ds_name=ds_name, split_type='train')
  File "/home/blackfoot/PycharmProjects/zsgnet-pytorch/code/dat_loader.py", line 84, in __init__
    self.image_data = self._read_annotations(csv_file)
  File "/home/blackfoot/PycharmProjects/zsgnet-pytorch/code/dat_loader.py", line 167, in _read_annotations
    sample = trn_data['query'].iloc[0]
  File "/home/blackfoot/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1768, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/blackfoot/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2138, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/blackfoot/.local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
Backend TkAgg is interactive backend. Turning interactive mode on.

Process finished with exit code 1

**Comment by bareblackfoot** [comment]
solved it :)
