### ISSUE TITLE
problem while reproducing referit dataset

### ISSUE THREAD

**Issue by YBYBZhang** [TheShadow29/zsgnet-pytorch#9]
Thank you for your great work. I meet some problems when I reproduced the result on referit dataset. I use the same config with [this file](https://github.com/TheShadow29/zsgnet-pytorch/blob/master/configs/cfg.json). 
However, the validation accuracy is only 50% after 20 epochs while it should be 58% in the paper. I think maybe the config is different among different datasets. Looking forward to your help !

**Comment by TheShadow29** [comment]
Hello,  @1170300521 sorry for the delayed reply (for some reason this didn't turn up in my notifs).

I recall using lr=1e-4 for 10 epochs, and 1e-5 for another 10 epochs.

I might have access to the logs, so let me know if you are having trouble reproducing the result.

**Comment by tejan-rgb** [comment]
@1170300521 @TheShadow29  I am having difficulty reproducing the result. I am trying to reproduce the result on Flickr30k.
Everything went fine till...

I ran ```python code/main_dist.py flickr30k_retina_29Jul19.pth --ds_to_use='refclef' --resume=True --only_valid=True --only_test=True```

and got an error:
```
Traceback (most recent call last):
  File "code/main_dist.py", line 101, in <module>
    fire.Fire(main_dist)
  File "/home/tejanm/anaconda3/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/tejanm/anaconda3/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/tejanm/anaconda3/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "code/main_dist.py", line 83, in main_dist
    cfg = update_from_dict(cfg, kwargs, key_maps)
  File "/home/tejanm/zsgnet-pytorch/code/extended_config.py", line 83, in update_from_dict
    assert subkey in d, f'key {full_key} doesnot exist'
AssertionError: key only_valid doesnot exist
```

Can you please help?

**Comment by TheShadow29** [comment]
@tejan-rgb Can you try changing `only_valid` to `only_val`?
